### ISSUE TITLE
Not able to create Lead

### ISSUE THREAD

**Issue by pooja-45-erp** [8848digital/erpnext#1416]
### Information about bug

![Image](https://github.com/user-attachments/assets/7f5fef4c-1063-4cf5-ac53-1d743e0cd6bc)

### Module

CRM

### Version

Frappe CRM: v2.0.0-dev (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell

```

**Comment by hrishikesh8848** [comment]
@pooja-45-erp this issue is fixed

**Comment by pooja-45-erp** [comment]
Still facing this issue , please the attached screenshot.

![Image](https://github.com/user-attachments/assets/64319f0b-b9fc-4c5d-acbf-c402b5c317d6)
