### ISSUE TITLE
Journal Entry | test_payment_of_gst_tds_TC_ACC_054 | AssertionError: Could not find IGST account: [{'name': '_Test Account VAT - _TC'}, {'name': '_Test Account Service Tax - _TC'}, {'name': '_Test Account Excise Duty - _TC'}, {'name': '_Test Account Education Cess - _TC'}, {'name': '_Test Account S&H Education Cess - _TC'}]

### ISSUE THREAD

**Issue by 8848jay** [8848digital/erpnext#2021]
### similar failed testcase:-
test_reversal_of_itc_TC_ACC_059

### Issue Details:
AssertionError: Could not find IGST account: [{'name': '_Test Account VAT - _TC'}, {'name': '_Test Account Service Tax - _TC'}, {'name': '_Test Account Excise Duty - _TC'}, {'name': '_Test Account Education Cess - _TC'}, {'name': '_Test Account S&H Education Cess - _TC'}]

### Traceback:
``` 
FAIL: test_payment_of_gst_tds_TC_ACC_054 (erpnext.accounts.doctype.journal_entry.test_journal_entry.TestJournalEntry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frappe/test-postgres/test-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/test_journal_entry.py", line 795, in test_payment_of_gst_tds_TC_ACC_054
    self.fail(f"Could not find IGST account: {tax_accounts}")
AssertionError: Could not find IGST account: [{'name': '_Test Account VAT - _TC'}, {'name': '_Test Account Service Tax - _TC'}, {'name': '_Test Account Excise Duty - _TC'}, {'name': '_Test Account Education Cess - _TC'}, {'name': '_Test Account S&H Education Cess - _TC'}, {'name': '_Test Vat - _TC'}]
```

**Comment by 8848jay** [comment]
retested and solved

**Comment by 8848jay** [comment]
This testcase failed :
test_reversal_of_itc_TC_ACC_059

```
FAIL: test_reversal_of_itc_TC_ACC_059 (erpnext.accounts.doctype.journal_entry.test_journal_entry.TestJournalEntry)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frappe/test-postgres/test-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/test_journal_entry.py", line 1043, in test_reversal_of_itc_TC_ACC_059
    self.fail(f"Could not find SGST or CGST accounts. Found: {tax_accounts}")
AssertionError: Could not find SGST or CGST accounts. Found: [{'name': '_Test Account VAT - _TC'}, {'name': '_Test Account Service Tax - _TC'}, {'name': '_Test Account Excise Duty - _TC'}, {'name': '_Test Account Education Cess - _TC'}, {'name': '_Test Account S&H Education Cess - _TC'}, {'name': '_Test Account IGST - _TC'}]
```

**Comment by swathibollineni2** [comment]
@8848jay Please check this issue is resolved or not

**Comment by 8848jay** [comment]
not resolved 
test_reversal_of_itc_TC_ACC_059 this testcase have issue already 
@swathibollineni2

**Comment by 8848jay** [comment]
retested and solved
