### ISSUE TITLE
TC_S_143, TC_S_142 - AssertionError: 1 != 2

### ISSUE THREAD

**Issue by swathibollineni2** [8848digital/erpnext#2433]
### Information about bug

======================================================================
FAIL: test_pr_to_so_with_applied_on_item_code_TC_S_143 (erpnext.accounts.doctype.pricing_rule.test_pricing_rule.TestPricingRule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pricing_rule/test_pricing_rule.py", line 1632, in test_pr_to_so_with_applied_on_item_code_TC_S_143
    self.assertEqual(len(so.items), 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 1 test in 2.970s

FAILED (failures=1)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.58.2 (pre-prod)

ERPNext CRM: v0.0.1 (pre-prod)

ERPNext India: v0.0.1 (pre-prod)

Frappe Framework: v15.63.1 (pre-prod)

India Compliance: v15.17.1 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (pre-prod)

Sales Commission: v0.0.1 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell

```

**Comment by swathibollineni2** [comment]
@ashishverma8848 Still getting same issue

**Comment by ashishverma8848** [comment]
@swathibollineni2  issue is resolved and Pr is raised once satya merge the code check again

**Comment by swathibollineni2** [comment]
@ashishverma8848 issue is still occurring in postgres instance

**Comment by swathibollineni2** [comment]
@ashishverma8848 test case passed in postgres instance
